# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name:  Github Reusable Workflows
site_description: A collection of reusable GitHub Actions workflows
docs_dir: docs/
site_author: DAI
site_url: https://tx-pts-dai.github.io/github-workflows/
repo_name: github-workflows
repo_url: https://github.com/tx-pts-dai/github-workflows

nav:
  - Overview: index.md
  - Getting Started: getting-started.md
  - Workflows:
    - AWS Secrets Copy: workflows/aws-secrets-copy.md
    - Docker Build and Push: workflows/docker-build-push.md
    - Terraform Plan and Apply: workflows/terraform.md
    - GitHub Release: workflows/github-release.md
    - Lambda Node Layer: workflows/lambda-build-node.md
  - Examples:
      - Terraform: examples/terraform.md
  - FAQ: faq.md
  - Test: test.md

theme:
  name: material
  logo: images/logo.png
  favicon: images/favicon.png
  font:
    text:
  palette:
    - scheme: default
      primary: indigo
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  features:
    - navigation.tabs.sticky
    - navigation.tabs
    - content.code.copy

plugins:
  - include-markdown
  - search:
      lang:
        - en
  - tags

markdown_extensions:
  - attr_list
  - admonition
  - codehilite
  - footnotes
  - md_in_html
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      check_paths: true
      # base_path: docs
  - pymdownx.superfences
  - toc:
      permalink: true