name: Test Reusable Single Environment Workflow

on:
  workflow_dispatch:
  # pull_request:
  #   branches:
  #     - main

jobs:
  config:
    uses: ./.github/workflows/lib-config.yaml
    with:
      config_path: .github/config_single.yaml

  check:
    needs: [config]
    uses: ./.github/workflows/lib-tf-check.yaml
    with:
      tf_dir: ${{ needs.config.outputs.tf_dir }}

  deploy_sandbox:
    if: github.event_name == 'pull_request'
    needs: [check]
    uses: ./.github/workflows/lib-tf-deploy-config.yaml
    with:
      environment: sandbox
      config_path: .github/config_single.yaml

  destroy_sandbox:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    uses: ./.github/workflows/lib-tf-destroy-config.yaml
    with:
      environment: sandbox
      config_path: .github/config_single.yaml
