on:
  workflow_call:
    inputs:
      config_path:
        description: 'Path to the config file'
        type: string
        required: false
        default: '.github/config.yaml'
      environment:
        description: 'Environment to run plan on'
        type: string
        required: true

permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs:
  plan:
    runs-on: ubuntu-latest
    name: ${{ inputs.environment }} - Plan
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get config
        id: config
        uses: tx-pts-dai/config-export-action@v0.0.2
        with:
          config_path: ${{ inputs.config_path }}
          environment: ${{ inputs.environment }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ steps.config.outputs.aws_account_id }}:role/${{ steps.config.outputs.aws_role_name }}
          aws-region: ${{ steps.config.outputs.aws_region }}

      - name: Terraform Plan
        uses: dflook/terraform-plan@v1
        with:
          path: ${{ steps.config.outputs.tf_dir }}
          label: ${{ inputs.environment }}
          add_github_comment: changes-only
          backend_config: |
            backend=s3
            bucket=${{ steps.config.outputs.tf_state_bucket }}
            key=${{ steps.config.outputs.tf_state_key }}
          variables: |
            environment="${{ inputs.environment }}"
            github_repo="${{ github.event.repository.name }}"
            region="${{ steps.config.outputs.aws_region }}"
          var_file: |
            ${{ steps.config.outputs.tf_dir }}/environment/${{ inputs.environment }}.tfvars
