name: TF Deployment
on:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"
      - "renovate.json"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "README.md"
      - "renovate.json"
  workflow_dispatch:
  
permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  plan:
    if: github.event_name == 'pull_request'
    strategy:
      fail-fast: false
      matrix:
        stack: [infra]
        environment: [dev, int, prod]
    uses: tx-pts-dai/github-workflows/.github/workflows/tf-plan.yaml@ece8993c7f7e419bc658a7036cd281f0ad0968b6 # v1.0.1
    with:
      environment: ${{ matrix.stack }}-${{ matrix.environment }}

  apply:
    if: github.ref_name == github.event.repository.default_branch && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
    strategy:
      fail-fast: false
      matrix:
        stack: [infra]
        environment: [dev, int, prod]
    uses: tx-pts-dai/github-workflows/.github/workflows/tf-apply.yaml@ece8993c7f7e419bc658a7036cd281f0ad0968b6 # v1.0.1
    with:
      environment: ${{ matrix.stack }}-${{ matrix.environment }}
