on:
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/_test-tf-dflook-feature.yaml'
      - '.github/workflows/tf-dflook-feature.yaml'
      - 'tests/terraform/**'

  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write
  pull-requests: write

jobs:
  test_tf_dflook_feature:
    uses: ./.github/workflows/tf-dflook-feature.yaml
    with:
      environment: sandbox
