on:
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/_test-tf-dflook-plan.yaml'
      - '.github/workflows/tf-dflook-plan.yaml'
      - 'tests/terraform/**'
  push:
    branches:
      - main

jobs:
  test_tf_dflook_plan:
    uses: ./.github/workflows/tf-dflook-plan.yaml
    with:
      environment: sandbox
