on:
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/_test-docker-build.yaml'
      - '.github/workflows/docker-build.yaml'
      - 'tests/terraform/**'
  push:
    branches:
      - main

jobs:
  test_docker_build:
    uses: ./.github/workflows/docker-build.yaml
    with:
      image_name: test-docker-build
      docker_context: tests/docker
      artifact_retention_days: 1
