on:
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/_test-docker.yaml"
      - ".github/workflows/docker-*.yaml"
      - "tests/docker/**"
  push:
    branches:
      - main

jobs:
  test_docker_build_push_ecr:
    uses: ./.github/workflows/docker-build-push-ecr.yaml
    with:
      aws_account_id: ${{ vars.aws_account_id }}
      aws_region: ${{ vars.aws_region }}
      aws_role_name: ${{ vars.aws_role_name }}
      image_name: test-docker-build-push
      image_tag: ${{ github.head_ref }}
      docker_context: tests/docker
      docker_push: false

  test_docker_build_push_ecr_no_image_tag:
    uses: ./.github/workflows/docker-build-push-ecr.yaml
    with:
      aws_account_id: ${{ vars.aws_account_id }}
      aws_region: ${{ vars.aws_region }}
      aws_role_name: ${{ vars.aws_role_name }}
      image_name: test-docker-build-push
      docker_context: tests/docker
      docker_push: false

  test_docker_build:
    uses: ./.github/workflows/docker-build.yaml
    with:
      image_name: test-docker-build
      docker_context: tests/docker
      artifact_retention_days: 1

  test_docker_build_secrets:
    uses: ./.github/workflows/docker-build-push-ecr.yaml
    secrets:
      docker_secrets: |
        SECRET_TOKEN=${{ secrets.TEST_SECRET_TOKEN }}
    with:
      aws_account_id: ${{ vars.aws_account_id }}
      aws_region: ${{ vars.aws_region }}
      aws_role_name: ${{ vars.aws_role_name }}
      docker_context: tests/docker
      dockerfile_path: tests/docker/secrets.Dockerfile
      docker_push: false
