on:
  workflow_run:
    workflows: [_test-tf-dflook-feature]
    types:
      - completed

jobs:
  test_tf_dflook_cleanup:
    uses: ./.github/workflows/tf-dflook-cleanup.yaml
    with:
      environment: sandbox
