on:
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/_test-docker-build-push-ecr.yaml'
      - '.github/workflows/docker-build-push-ecr.yaml'
      - 'tests/terraform/**'
  push:
    branches:
      - main

jobs:
  test_docker_build_push_ecr:
    uses: ./.github/workflows/docker-build-push-ecr.yaml
    with:
      aws_account_id: ${{ vars.aws_account_id }}
      aws_region: ${{ vars.aws_region }}
      aws_role_name: ${{ vars.aws_role_name }}
      image_name: test-docker-build-push
      image_tag: ${{ github.head_ref }}
      docker_context: tests/docker
      docker_push: false

  test_docker_build_push_ecr_no_image_tag:
    uses: ./.github/workflows/docker-build-push-ecr.yaml
    with:
      aws_account_id: ${{ vars.aws_account_id }}
      aws_region: ${{ vars.aws_region }}
      aws_role_name: ${{ vars.aws_role_name }}
      image_name: test-docker-build-push
      docker_context: tests/docker
      docker_push: false
