on:
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/_test-aws-secrets-copy.yaml'
      - '.github/workflows/aws-secrets-copy.yaml'
  push:
    branches:
      - main

env:

jobs:
  create_dummy_secret:
    name: Create the source secret
    runs-on: ubuntu-latest
    environment: sandbox
    env:
      SECRET_NAME: "tmp-source-${{ github.sha }}"
      SECRET_VALUE: "{username:sample,password:sample}"
      DESCRIPTION: "dummy value to test workflow. This secret can be deleted"
    steps:
      - name: aws login
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4
        with:
          aws-region: "eu-central-1"
      - name: create_secret
        run: |
          aws secretsmanager create-secret --name "$SECRET_NAME" --secret-string "$SECRET_VALUE"
          aws secretsmanager update-secret --name "$SECRET_NAME" --description "$DESCRIPTION"

      - name: delete_secret
        run: |
          echo aws secretsmanager delete-secret --secret-id "$SECRET_NAME" --force-delete-without-recovery

  copy_secret:
    needs: create_dummy_secret
    uses: ./.github/workflows/aws-secrets-copy.yaml
    with:
      source_aws_region: "eu-central-1"
      source_aws_oidc_role_arn: ""
      source_secret_name: "tmp-source-${{ github.sha }}"
      destination_aws_region: "eu-central-1"
      destination_aws_oidc_role_arn: ""
      destination_secret_name: "tmp-dest-new-${{ github.sha }}"
      secret_description: "can be deleted, explicit dest description"
      aws_tags: "Created,Manually;Creator,Github workflow"
