# TODO: Setup access to dai sanbox account
name: Test Reusable Workflows

on:
  pull_request:
    branches:
      - main

jobs:
  test_terraform_deploy_basic:
    uses: ./.github/workflows/tf-deploy-basic.yaml
    with:
      github_artifact_path: path/to/artifacts
      aws_account_id: 911453050078
      aws_region: us-east-1
      aws_role_name: cicd-iac
      environment: sandbox
      tf_deploy_override: true
      tf_dir: tests/terraform
      tf_state_bucket: tf-state-911453050078
      tf_state_key: tests/test_terraform_deploy_basic.tfstate
      tf_version: 1.5.6

  test_docker_build:
    uses: ./.github/workflows/docker-build.yaml
    with:
      image_name: test-docker-build
      docker_context: tests/docker
      artifact_retention_days: 1


  test_docker_push_ecr:
    needs: test_docker_build
    uses: ./.github/workflows/docker-push-ecr.yaml
    with:
      aws_account_id: 911453050078
      aws_region: us-east-1
      aws_role_name: cicd-iac
      image_name: test-docker-build
      image_tag: ${{ github.sha }}

  config_export:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Config Export
      id: config_export
      uses: tx-pts-dai/config-export-action@v0.0.2
      with:
        config_path: .github/config.yaml
        environment: sandbox

    - name: Output Config
      run: echo "tf_state_bucket:${{ steps.config_export.outputs.tf_state_bucket }}"
