on:
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/_test-tf.yaml"
      - ".github/workflows/tf-*.yaml"
      - "tests/terraform/**"

jobs:
  test_tf_feature:
    uses: ./.github/workflows/tf-feature.yaml
    with:
      environment: sandbox
      tf_workspace: test/slash/replacement

  test_tf_outputs:
    needs: test_tf_feature
    runs-on: ubuntu-latest
    steps:
      - name: Show Terraform Outputs
        run: echo "${{ needs.test_tf_feature.outputs.tf_outputs }}"

  test_tf_outputs_decode_random_pet:
    needs: test_tf_feature
    runs-on: ubuntu-latest
    steps:
      - name: Show random_pet output resource
        run: echo "${{ fromJson(needs.test_tf_feature.outputs.tf_outputs).random_pet }}"

  test_tf_plan:
    needs: test_tf_feature
    uses: ./.github/workflows/tf-plan.yaml
    with:
      environment: sandbox

  test_tf_apply:
    needs: test_tf_plan
    uses: ./.github/workflows/tf-apply.yaml
    with:
      environment: sandbox
      tf_pre_run: curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && unzip -qq awscliv2.zip && ./aws/install

  test_tf_cleanup:
    needs: test_tf_apply
    uses: ./.github/workflows/tf-cleanup.yaml
    with:
      environment: sandbox
      tf_workspace: test/slash/replacement

  test_upload_artifact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/upload-artifact@v4
        with:
          name: docker-artifacts
          path: tests/docker-artifacts/artifact-sample.txt

  test_tf_artifact:
    needs: test_upload_artifact
    uses: ./.github/workflows/tf-plan.yaml
    with:
      environment: sandbox
      tf_dir: tests/terraform/artifact
      gh_artifact_name: docker-artifacts
      gh_artifact_path: tests/terraform/artifact/
      tf_vars: |
        file_path="artifact-sample.txt"

  test_tf_artifact_all:
    needs: test_upload_artifact
    uses: ./.github/workflows/tf-plan.yaml
    with:
      environment: sandbox
      tf_dir: tests/terraform/artifact
      gh_artifact_path: tests/terraform/artifact/
      tf_vars: |
        file_path="docker-artifacts/artifact-sample.txt"
