name: Copy AWS secret
# Copy an AWS secret from one AWS account to another
on:
  workflow_call:
    inputs:
      source_aws_region:
        description: "AWS Region"
        type: string
      source_aws_oidc_role_arn:
        description: "AWS OIDC IAM role to assume"
        type: string
      source_secret_name:
        description: "AWS secret name to copy from"
        type: string
      destination_aws_region:
        description: "AWS Region"
        type: string
      destination_aws_oidc_role_arn:
        description: "AWS OIDC IAM role to assume"
        type: string
      destination_secret_name:
        description: "AWS secret name to copy to"
        type: string
      aws_tags:
        description: "Tags to put on the created secret"
        type: string
jobs:
  copy-aws-secret:
    name: Copy AWS secret
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    steps:
      - name: Configure Source AWS credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4
        with:
          role-to-assume: ${{ inputs.source_aws_oidc_role_arn }}
          aws-region: ${{ inputs.source_aws_region }}

      - name: Get secret
        id: get-secret
        run: aws secretsmanager get-secret-value --output json --secret-id ${{ inputs.source_scret_name }} --query SecretString | jq -r '.' > ${{ env.SECRET_FILE }}

      - name: Get secret 2
        uses: aws-actions/aws-secretsmanager-get-secrets@v2
        with:
          secret-ids: |
            SOURCE_SECRET, ${{ inputs.source_secret_name }}

      - name: Test Source
        run: |
          echo running on aws account $(aws sts get-caller-identity)
          echo secret in env: $SOURCE_SECRET
          echo secret in file: $(cat ${{ env.SECRET_FILE }})

      - name: Configure Destination AWS credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4
        with:
          role-to-assume: ${{ inputs.destination_aws_oidc_role_arn }}
          aws-region: ${{ inputs.destination_aws_region }}

      - name: Test Source
        run: |
          echo running on aws account $(aws sts get-caller-identity)
