name: Docker Build

on:
  workflow_call:
    inputs:
      environment:
        description: "Environment to deploy"
        type: string
      image_name:
        description: "Name of the Docker image to build"
        type: string
      docker_context:
        description: "Path to the build context"
        type: string
      artifact_retention_days:
        description: "Number of days to retain the artifact"
        type: number
      docker_target:
        description: "Build target"
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Check out code
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d70bba72b1f3fd22344832f00baa16ece964efeb # v3

      - name: Build and export
        uses: docker/build-push-action@31159d49c0d4756269a0940a750801a1ea5d7003 # v6
        env:
          DOCKER_CTX: ${{ inputs.docker_context || vars.docker_context || '.'}}
          IMAGE_NAME: ${{ inputs.image_name || vars.image_name || github.event.repository.name }}
          DOCKER_TARGET: ${{ inputs.docker_target || vars.docker_target }}
        with:
          context: ${{ env.DOCKER_CTX }}
          # platforms: linux/amd64,linux/arm64 # TODO add support for multi-arch builds
          tags: ${{ env.IMAGE_NAME }}:${{ github.sha }}
          outputs: type=docker,dest=/tmp/${{ env.IMAGE_NAME }}.tar
          cache-from: type=gha
          cache-to: type=gha,mode=max
          target: ${{ env.DOCKER_TARGET }}

      - name: Upload artifact
        env:
          IMAGE_NAME: ${{ inputs.image_name || vars.image_name || github.event.repository.name }}
          ARTIFACT_RETENTION_DAYS: ${{ inputs.artifact_retention_days || vars.artifact_retention_days || 5 }}
        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4
        with:
          name: ${{ env.IMAGE_NAME }}-${{ github.sha }}
          path: /tmp/${{ env.IMAGE_NAME }}.tar
          retention-days: ${{ env.ARTIFACT_RETENTION_DAYS }}
