# Default release on push in main
name: Release
on:
  push:
    branches:
    - main
    
jobs:
 release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
    - name: Checkout
      uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
      
    - name: Retrieve version
      id: version 
      run: | 
        git fetch --tags
        RELEASE_TAG=$(git tag | sort -V | tail -1 | awk -F. '{print $1"."($2+1)"."$3}')
        if [ "$RELEASE_TAG" = "" ]; then 
          echo "TAG_NAME=v0.0.1" >> $GITHUB_OUTPUT
        else
          echo "TAG_NAME=$RELEASE_TAG">> $GITHUB_OUTPUT
        fi;
      
    - name: Release
      uses: softprops/action-gh-release@69320dbe05506a9a39fc8ae11030b214ec2d1f87 # v2
      with:
        tag_name: ${{ steps.version.outputs.TAG_NAME }}
        generate_release_notes: true
