# Default release on push in main
name: Release
on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4

      - name: Determine version increment
        id: version_increment
        run: |
          git fetch --tags
          CURRENT_TAG=$(git tag | sort -V | tail -1)
          if [ "$CURRENT_TAG" = "" ]; then
            CURRENT_TAG="v0.0.1"
          fi

          BRANCH_NAME=$(echo $GITHUB_REF | awk -F/ '{print $3}')
          if [[ "$BRANCH_NAME" == fix* ]]; then
            INCREMENT="patch"
          elif [[ "$BRANCH_NAME" == feat* ]]; then
            INCREMENT="minor"
          else
            return 0
          fi

          MAJOR=$(echo $CURRENT_TAG | awk -F. '{print $1}')
          MINOR=$(echo $CURRENT_TAG | awk -F. '{print $2}')
          PATCH=$(echo $CURRENT_TAG | awk -F. '{print $3}')

          if [ "$INCREMENT" = "patch" ]; then
            PATCH=$((PATCH + 1))
          elif [ "$INCREMENT" = "minor" ]; then
            MINOR=$((MINOR + 1))
            PATCH=0
          fi

          NEW_TAG="$MAJOR.$MINOR.$PATCH"
          echo "NEW_TAG=$NEW_TAG" >> $GITHUB_OUTPUT

          MAJOR_VERSION=$(echo $NEW_TAG | awk -F. '{print $1}')
          MINOR_VERSION=$(echo $NEW_TAG | awk -F. '{print $1"."$2}')
          echo "MAJOR_VERSION=$MAJOR_VERSION" >> $GITHUB_ENV
          echo "MINOR_VERSION=$MINOR_VERSION" >> $GITHUB_ENV

      - name: Release
        uses: softprops/action-gh-release@69320dbe05506a9a39fc8ae11030b214ec2d1f87 # v2
        with:
          tag_name: ${{ steps.version_increment.outputs.NEW_TAG }}
          generate_release_notes: true

      - name: Update major and minor version tags
        run: |
          git tag -fa ${{ env.MAJOR_VERSION }} -m "Update major version tag"
          git push origin ${{ env.MAJOR_VERSION }} --force
          git tag -fa ${{ env.MINOR_VERSION }} -m "Update minor version tag"
          git push origin ${{ env.MINOR_VERSION }} --force
