name: Release

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Retrieve PR title
        id: pr_title
        run: echo "PR_TITLE=${{ github.event.pull_request.title }}" >> $GITHUB_ENV

      - name: Determine version increment
        id: version_increment
        run: |
          git fetch --tags
          CURRENT_TAG=$(git tag | sort -V | tail -1)
          if [ "$CURRENT_TAG" = "" ]; then
            CURRENT_TAG="v0.0.1"
          fi

          MAJOR=$(echo $CURRENT_TAG | awk -F. '{print $1}')
          MINOR=$(echo $CURRENT_TAG | awk -F. '{print $2}')
          PATCH=$(echo $CURRENT_TAG | awk -F. '{print $3}')

          PR_TITLE=$PR_TITLE
          RELEASE=true
          if [[ "$PR_TITLE" =~ ^fix ]]; then
            PATCH=$((PATCH + 1))
          elif [[ "$PR_TITLE" =~ ^feat ]]; then
            MINOR=$((MINOR + 1))
            PATCH=0
          else
            echo "Nothing to release"
            RELEASE=false
            return 0
          fi

          NEW_TAG="$MAJOR.$MINOR.$PATCH"
          MAJOR_VERSION=$(echo $NEW_TAG | awk -F. '{print $1}')
          MINOR_VERSION=$(echo $NEW_TAG | awk -F. '{print $1"."$2}')

          echo "RELEASE=true" >> $GITHUB_OUTPUT
          echo "NEW_TAG=$NEW_TAG" >> $GITHUB_OUTPUT
          echo "MAJOR_VERSION=$MAJOR_VERSION" >> $GITHUB_ENV
          echo "MINOR_VERSION=$MINOR_VERSION" >> $GITHUB_ENV

      - name: Release
        if: steps.version_increment.outputs.RELEASE == 'true'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version_increment.outputs.NEW_TAG }}
          generate_release_notes: true

      - name: Update major and minor version tags
        if: steps.version_increment.outputs.RELEASE == 'true'
        run: |
          git tag -fa ${{ env.MAJOR_VERSION }} -m "Update major version tag"
          git push origin ${{ env.MAJOR_VERSION }} --force
          git tag -fa ${{ env.MINOR_VERSION }} -m "Update minor version tag"
          git push origin ${{ env.MINOR_VERSION }} --force
