name: Build Lambda Layer
on:
  workflow_call:
    inputs:
      environment:
        description: "Environment to deploy."
        type: string
      node_version:
        description: "The Node.js version to use"
        type: string
        default: "20"
      source_dir:
        description: "The directory where the Lambda source code is located"
        type: string
      build_dir:
        description: "The directory where the Lambda build artifacts are located"
        type: string
      artifact_retention_days:
        description: "Number of days to retain the artifact"
        type: number
jobs:
  build:
    name: Build Lamda Layer
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    env:
      NODE_VERSION: ${{ inputs.node_version }}
      BUILD_DIR: ${{ inputs.build_dir || vars.build_dir || 'dist'}}
      SOURCE_DIR: ${{ inputs.source_dir || vars.source_dir || 'src'}}
    defaults:
      run:
        working-directory: ${{ inputs.source_dir || vars.source_dir || 'src'}}
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Build
        id: build
        run: |
          fname=$(basename ${{ env.SOURCE_DIR }})
          fpath=${{ env.BUILD_DIR }}/$fname-v${{ env.NODE_VERSION }}.zip
          mkdir -p nodejs ${{ env.BUILD_DIR }}
          npm install --omit=dev
          cp -RL node_modules nodejs/
          zip -r $fpath nodejs
          echo "file_name=$fname" >> $GITHUB_OUTPUT
          echo "file_path=$fpath" >> $GITHUB_OUTPUT

      - name: Archive
        env:
          NODE_VERSION: ${{ inputs.node_version }}
          SOURCE_DIR: ${{ inputs.source_dir || vars.source_dir || 'src' }}
          ARTIFACT_RETENTION_DAYS: ${{ inputs.artifact_retention_days || vars.artifact_retention_days || 5}}
        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4
        with:
          name: ${{ steps.build.outputs.file_name }}-${{ env.NODE_VERSION }}
          path: ${{ env.SOURCE_DIR }}/${{ steps.build.outputs.file_path }}
          if-no-files-found: error
          retention-days: ${{ env.ARTIFACT_RETENTION_DAYS }}
