name: Build NodeJS Lambda
on:
  workflow_call:
    inputs:
      node_version:
        description: "NodeJS version"
        type: string
        default: "20"
      source_dir:
        description: "Directory of the Lambda source code"
        type: string
        required: true
      gh_artifact_name:
        description: "Name of the artifact to upload"
        type: string
      gh_artifact_path:
        description: "A file, directory or wildcard pattern that describes what to upload"
        type: string
        default: "**/lambda.zip"
      gh_artifact_retention_days:
        description: "Number of days to retain the artifact"
        type: number
        default: 30
jobs:
  build:
    name: Build NodeJS
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: ${{ inputs.node_version }}
      SOURCE_DIR: ${{ inputs.source_dir }}
    defaults:
      run:
        working-directory: ${{ env.SOURCE_DIR }}
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Build
        id: build
        run: |
          npm install --omit=dev
          zip -r lambda.zip .

      - name: Archive
        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4
        with:
          name: ${{ inputs.gh_artifact_name }}
          path: ${{ inputs.gh_artifact_path }}
          if-no-files-found: error
          retention-days: ${{ inputs.gh_artifact_retention_days }}
