name: Deploy

on:
  workflow_call:
    inputs:
      environment:
        description: 'Environment to deploy to'
        type: string
        required: true

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  deploy:
    uses: tx-pts-dai/github-workflows/.github/workflows/test.yaml@nested-wf
    with:
      environment: ${{ github.event.inputs.environment }}
