name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - main
    paths:
      - docs/**
      - README.md
      - mkdocs.yaml
      - .github/workflows/publish-docs.yaml

env:
  PYTHON_VERSION: 3.x

permissions:
  contents: read

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout main
        uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2
        with:
          fetch-depth: 0

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r docs/requirements.txt

      - name: git config
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - run: mkdocs gh-deploy --force
