name: Terraform
on:
  workflow_call:
    inputs:
      aws-region:
        description: 'The AWS region'
        type: string
        required: false
        default: eu-central-1

      aws-role-duration-seconds:
        description: 'Session duration to request for the give role'
        type: number
        required: false
        default: 7200

      aws-role-arn:
        description: 'ARN of the role to assume'
        type: string
        required: false
        default: ''

      tflint-version:
        description: 'tflint version to use'
        type: string
        required: false
        default: v0.48.0

      terraform-dir:
        description: 'The directory where the Terraform files are located'
        type: string
        required: false
        default: .

      terraform-version:
        # should we compute it from the main.tf files ? or tfenv ? or latest ?
        description: 'The Terraform version to use'
        type: string
        required: false
        default: 1.6.1

      terraform-init-parameters:
        description: 'The terraform init parameters'
        type: string
        required: false
        default: ''

      terraform-var-file:
        description: 'The terraform apply/plan/validate var file to use'
        type: string
        required: false
        default: ''

      terraform-var:
        description: 'The terraform apply/plan var to use'
        type: string
        required: false
        default: ''

      github-default-branch:
        description: 'default branch of the repos'
        type: string
        required: false
        default: main

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.head_ref || github.run_id }}
      cancel-in-progress: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials via IAM role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ inputs.aws-role-arn }}
          aws-region: ${{ inputs.aws-region }}

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ inputs.terraform-version }}

      - name: Terraform Init
        id: init
        run: >
          terraform
          -chdir=${{ inputs.terraform-dir }}
          init
          -input=false
          ${{ inputs.terraform-init-parameters }}

      - name: Terraform Format
        id: fmt
        run: >
          terraform
          -chdir=${{ inputs.terraform-dir }}
          fmt
          -check
          -recursive

      - name: Terraform Validate
        id: validate
        run: >
          terraform
          -chdir=${{ inputs.terraform-dir }}
          validate

      - name: Terraform Plan
        id: plan
        if: github.event_name == 'pull_request'
        run: >
          terraform
          -chdir=${{ inputs.terraform-dir }}
          plan
          -input=false
          -lock=false
          -var-file="${{ inputs.terraform-var-file }}
          ${{ inputs.terraform-var }} -out=tfplan < /dev/null

      - name: Terraform Apply
        if: github.ref == 'refs/heads/${{ inputs.github-default-branch }}' && github.event_name == 'push'
        run: >
          terraform
          -chdir='${{ inputs.terraform-dir }}'
          apply
          -input=tfplan < /dev/null
