# Workflow to deploy feature branches
# Creates a new terraform workspace based on the branch name
# This workflow utilizes github environments to store secrets and varibles.
on:
  workflow_call:
    inputs:
      environment:
        description: "Environment to deploy to"
        type: string
        required: true
      aws_region:
        description: "AWS region"
        type: string
        default: "eu-central-1"
      aws_oidc_role_arn:
        description: "AWS OIDC IAM role to assume"
        type: string
        default: "${{ vars.AWS_OIDC_ROLE_ARN }}"
      build_type:
        description: "Type of build: Docker | Lambda"
        type: string
        default: "${{ vars.BUILD_TYPE }}"
      tf_dir:
        description: "Terraform directory"
        type: string
        default: "${{ vars.TF_DIR }}"
      tf_backend_configs:
        description: "Terraform backend config cli arguments"
        type: string
        default: "${{ vars.TF_BACKEND_CONFIGS }}"
      tf_var_files:
        description: "New line separated list of terraform variable files"
        type: string
        default: "${{ vars.TF_VAR_FILES }}"

jobs:
  terraform:
    permissions:
      contents: read
      id-token: write
      pull-requests: write
    concurrency:
      group: ${{ github.workflow }}-${{ inputs.environment }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ inputs.aws_oidc_role_arn }}
          aws-region: ${{ inputs.aws_region }}

      - name: Use branch workspace
        uses: dflook/terraform-new-workspace@v1
        with:
          path: ${{ inputs.tf_dir }}
          workspace: ${{ github.head_ref }}
          backend_config: ${{ inputs.tf_backend_configs }}

      - name: Deploy test infrastrucutre
        uses: dflook/terraform-apply@v1
        with:
          path: ${{ inputs.tf_dir }}
          workspace: ${{ github.head_ref }}
          backend_config: ${{ inputs.tf_backend_configs }}
          auto_approve: true
